version: "3"

services:
  cvweb:
    image: lab/sharecvweb:latest
    container_name: sharecvweb
    privileged: true
    restart: always
    ports:
      - "6002:3000"
    networks:
      app:
        ipv4_address: 172.18.0.22

networks:
  app:
    ipam:
      config:
        - subnet: 172.28.0.0/24
    external: true