// Code generated by goctl. DO NOT EDIT.
package types

type Pagination struct {
	Page  int64 `json:"page"`  // 页数
	Size  int64 `json:"size"`  // 条数
	Total int64 `json:"total"` // 总记录
}

type User struct {
	UserId            string `json:"userId"`            // 用户标识
	Email             string `json:"email"`             // 邮箱
	Mobile            string `json:"mobile"`            // 手机号
	MobileCountryId   string `json:"mobileCountryId"`   // 手机国家id
	MobileCountryName string `json:"mobileCountryName"` // 手机国家名称
	MobileCountryNum  string `json:"mobileCountryNum"`  // 手机国家区号
	UserType          string `json:"userType"`          // 用户类型 1=邮箱 2=手机 3=谷歌 4=苹果
	InvitationCode    string `json:"invitationCode"`    // 邀请码
}

type UserInfo struct {
	UserId           string `json:"userId"`           // 用户标识
	FirstName        string `json:"firstName"`        // 姓
	LastName         string `json:"lastName"`         // 名
	Nickname         string `json:"nickname"`         // 昵称
	Avatar           string `json:"avatar"`           // 头像
	BackgroundImg    string `json:"backgroundImg"`    // 背景
	Height           int64  `json:"height"`           // 身高
	Weight           int64  `json:"weight"`           // 体重
	Gender           int64  `json:"gender"`           // 性别 1=女 2=男 3=保密
	ModeType         int64  `json:"modeType"`         // 是否公开 1=公开 2=隐藏
	Birthday         string `json:"birthday"`         // 生日
	CountryId        int64  `json:"countryId"`        // 国家表id
	CountryName      string `json:"countryName"`      // 国家名称
	EmploymentId     int32  `json:"employmentId"`     // 求职类型表id
	Identity         int64  `json:"identity"`         // 用户身份 1=求职者或约会者 2=学生 3=招聘方
	Province         string `json:"province"`         // 省份
	City             string `json:"city"`             // 城市
	Address          string `json:"address"`          // 详细地点
	PersonalStrength string `json:"personalStrength"` // 个人实力
	PurposeCity      string `json:"purposeCity"`      // 意向城市 多个用英语逗号分割
	Interests        string `json:"interests"`        // 兴趣爱好 多个用英语逗号分割
	Languages        string `json:"languages"`        // 会的语言 多个用英语逗号分割
	DatingTargets    string `json:"datingTargets"`    // 交友的目 多个用英语逗号分割
	PersonalSkills   string `json:"personalSkills"`   // 个人技能 多个用英语逗号分割
	Views            int64  `json:"views"`            // 被浏览次数统计
}

type OtherUserInfo struct {
	FirstName        string `json:"firstName"`        // 姓
	LastName         string `json:"lastName"`         // 名
	Nickname         string `json:"nickname"`         // 昵称
	Avatar           string `json:"avatar"`           // 头像
	BackgroundImg    string `json:"backgroundImg"`    // 背景
	Height           int64  `json:"height"`           // 身高
	Weight           int64  `json:"weight"`           // 体重
	Gender           int64  `json:"gender"`           // 性别 1=女 2=男 3=保密
	Birthday         string `json:"birthday"`         // 生日
	CountryId        int64  `json:"countryId"`        // 国家表id
	CountryName      string `json:"countryName"`      // 国家名称
	EmploymentId     int32  `json:"employmentId"`     // 求职类型表id
	Identity         int64  `json:"identity"`         // 用户身份 1=求职者 2=学生 3=招聘方
	Province         string `json:"province"`         // 省份
	City             string `json:"city"`             // 城市
	Address          string `json:"address"`          // 详细地点
	PersonalStrength string `json:"personalStrength"` // 个人实力
	PurposeCity      string `json:"purposeCity"`      // 意向城市 多个用英语逗号分割
	Interests        string `json:"interests"`        // 兴趣爱好 多个用英语逗号分割
	Languages        string `json:"languages"`        // 会的语言 多个用英语逗号分割
	DatingTargets    string `json:"datingTargets"`    // 交友的目 多个用英语逗号分割
	PersonalSkills   string `json:"personalSkills"`   // 个人技能 多个用英语逗号分割
}

type StatusResp struct {
	Status int64 `json:"status"` // 状态 0 失败
}

type CodeResp struct {
	Status int64  `json:"status"` // 状态 0 失败
	Code   string `json:"code"`   // 验证码
}

type IdResp struct {
	Id int64 `json:"id"` // 新增主键 0 失败 >0 成功
}

type OssResp struct {
	StatusCode      int    `json:"StatusCode"`
	ErrorCode       string `json:"ErrorCode"`
	ErrorMessage    string `json:"ErrorMessage"`
	AccessKeyId     string `json:"AccessKeyId"`
	AccessKeySecret string `json:"AccessKeySecret"`
	SecurityToken   string `json:"SecurityToken"`
	Expiration      string `json:"Expiration"`
}

type OssUploadResp struct {
	FilePath string `json:"filePath"` // 文件路径
}

type Country struct {
	Id   int64  `json:"id"`   // 国家ID
	Code string `json:"code"` // 国家代码
	Num  string `json:"num"`  // 国家区号
	Name string `json:"name"` // 国家
}

type CountryListResp struct {
	List []Country `json:"list"` // 国家集合
}

type Language struct {
	Id          int64  `json:"id"`          // 语言ID
	Code        string `json:"code"`        // 语言简称
	FullCode    string `json:"fullCode"`    // 语言全称
	CountryCode string `json:"countryCode"` // 国家代码
	Name        string `json:"name"`        // 语言
}

type LanguageListResp struct {
	List []Language `json:"list"` // 语言集合
}

type ConfigResp struct {
	ApiUrls           []string `json:"apiUrls"`           // 接口跟地址
	WebUrls           []string `json:"webUrls"`           // web跟地址
	OssAuthUrl        string   `json:"ossAuthUrl"`        // oss授权地址
	OssBucketName     string   `json:"ossBucketName"`     // oss储存桶名称
	OssBucketUrl      string   `json:"ossBucketUrl"`      // oss储存桶域名
	OssBucketEndpoint string   `json:"ossBucketEndpoint"` // oss储存桶地域节点
}

type RegisterEmailReq struct {
	Email          string `json:"email" validate:"required,min=2,max=100" label:"邮箱"`                    // 邮箱 2-100
	Code           string `json:"code" validate:"required,min=4,max=6" label:"验证码"`                      // 验证码 4-6
	Password       string `json:"password" validate:"required,min=6,max=32" label:"密码"`                  // 密码 6-32
	InvitationCode string `json:"invitationCode,optional" validate:"omitempty,min=9,max=10" label:"邀请码"` // 上级邀请码
}

type CheckEmailReq struct {
	Email         string `json:"email" validate:"required,min=2,max=100" label:"邮箱"`                 // 邮箱 2-100
	GoogleCaptcha string `json:"googleCaptcha" validate:"required,min=6,max=2000" label:"谷歌验证Token"` // 谷歌验证Token
}

type SendCodeEmailReq struct {
	Email         string `json:"email" validate:"required,min=2,max=100" label:"邮箱"`                 // 邮箱 2-100
	GoogleCaptcha string `json:"googleCaptcha" validate:"required,min=6,max=2000" label:"谷歌验证Token"` // 谷歌验证Token
}

type SendCodePhoneReq struct {
	Phone         string `json:"phone" validate:"required,min=4,max=30" label:"手机号"`                 // 手机号 4-30
	PhoneNum      string `json:"phoneNum" validate:"required,min=1,max=10" label:"手机国家编号"`           // 手机国家编号 1-10
	GoogleCaptcha string `json:"googleCaptcha" validate:"required,min=6,max=2000" label:"谷歌验证Token"` // 谷歌验证Token
}

type CheckCodeEmailReq struct {
	Email         string `json:"email" validate:"required,min=2,max=100" label:"邮箱"`                 // 邮箱 2-100
	Code          string `json:"code" validate:"required,min=4,max=6" label:"验证码"`                   // 验证码
	GoogleCaptcha string `json:"googleCaptcha" validate:"required,min=6,max=2000" label:"谷歌验证Token"` // 谷歌验证Token
}

type CheckCodePhoneReq struct {
	Phone         string `json:"phone" validate:"required,min=4,max=30" label:"手机号"`                 // 手机号 4-30
	PhoneNum      string `json:"phoneNum" validate:"required,min=1,max=10" label:"手机国家编号"`           // 手机国家编号 1-10
	Code          string `json:"code" validate:"required,min=4,max=6" label:"验证码"`                   // 验证码
	GoogleCaptcha string `json:"googleCaptcha" validate:"required,min=6,max=2000" label:"谷歌验证Token"` // 谷歌验证Token
}

type ForgetPasswordReq struct {
	Email    string `json:"email" validate:"required,min=2,max=100" label:"邮箱"`   // 邮箱 2-100
	Password string `json:"password" validate:"required,min=6,max=32" label:"密码"` // 密码 6-32
	Code     string `json:"code" validate:"required,min=4,max=6" label:"验证码"`     // 验证码
}

type ChangePasswordReq struct {
	Email         string `json:"email" validate:"required,min=2,max=100" label:"邮箱"`                 // 邮箱 2-100
	GoogleCaptcha string `json:"googleCaptcha" validate:"required,min=6,max=2000" label:"谷歌验证Token"` // 谷歌验证Token
	OldPassword   string `json:"oldPassword" validate:"required,min=6,max=32" label:"旧密码"`           // 旧密码 6-32
	NewPassword   string `json:"newPassword" validate:"required,min=6,max=32" label:"新密码"`           // 新密码 6-32
}

type ChangeEmailWithCodeReq struct {
	NewEmail string `json:"newEmail" validate:"required,min=2,max=100" label:"新邮箱"` // 新邮箱 2-100
	Code     string `json:"code" validate:"required,min=4,max=6" label:"新邮箱验证码"`    // 新邮箱验证码
}

type ChangeEmailWithPasswordReq struct {
	NewEmail    string `json:"newEmail" validate:"required,min=2,max=100" label:"新邮箱"`  // 新邮箱 2-100
	OldPassword string `json:"oldPassword" validate:"required,min=4,max=6" label:"旧密码"` // 旧密码
	NewPassword string `json:"newPassword" validate:"required,min=4,max=6" label:"新密码"` // 新密码
}

type LoginEmailCodeReq struct {
	Email         string `json:"email" validate:"required,min=2,max=100" label:"邮箱"`                 // 邮箱 2-100
	Code          string `json:"code" validate:"required,min=4,max=6" label:"验证码"`                   // 验证码 4-6
	GoogleCaptcha string `json:"googleCaptcha" validate:"required,min=6,max=2000" label:"谷歌验证Token"` // 谷歌验证Token
	DeviceId      string `json:"deviceId" validate:"required,min=10,max=100" label:"设备UUID"`         // 设备UUID
	AppVersion    string `json:"appVersion" validate:"required,min=1,max=15" label:"app版本"`          // appVersion
	SystemVersion string `json:"systemVersion" validate:"required,min=1,max=15" label:"system版本"`    // systemVersion
	Platform      int64  `json:"platform" validate:"required,gte=0,lte=15" label:"登录平台"`             // 登录平台 1 pc 2 win 3 iOS 4 android 5 iPad 6 mac
}

type LoginEmailPasswordReq struct {
	Email         string `json:"email" validate:"required,min=2,max=100" label:"账号"`                 // 邮箱 2-100
	Password      string `json:"password" validate:"required,min=6,max=32" label:"密码"`               // 密码 6-32
	GoogleCaptcha string `json:"googleCaptcha" validate:"required,min=6,max=2000" label:"谷歌验证Token"` // 谷歌验证Token
	DeviceId      string `json:"deviceId" validate:"required,min=10,max=100" label:"设备UUID"`         // 设备UUID
	AppVersion    string `json:"appVersion" validate:"required,min=1,max=15" label:"app版本"`          // appVersion
	SystemVersion string `json:"systemVersion" validate:"required,min=1,max=15" label:"system版本"`    // systemVersion
	Platform      int64  `json:"platform" validate:"required,gte=0,lte=15" label:"登录平台"`             // 登录平台 1 pc 2 win 3 iOS 4 android 5 iPad 6 mac
}

type LoginGoogleReq struct {
	AccessToken   string `json:"accessToken" validate:"required,min=2,max=200" label:"谷歌授权Token"` // 谷歌授权Token
	IdToken       string `json:"idToken" validate:"required,min=2,max=200" label:"谷歌授权IdToken"`   // 谷歌授权IdToken
	DeviceId      string `json:"deviceId" validate:"required,min=10,max=100" label:"设备UUID"`      // 设备UUID
	AppVersion    string `json:"appVersion" validate:"required,min=1,max=15" label:"app版本"`       // appVersion
	SystemVersion string `json:"systemVersion" validate:"required,min=1,max=30" label:"system版本"` // systemVersion
	Platform      int64  `json:"platform" validate:"required,gte=0,lte=15" label:"登录平台"`          // 登录平台 1 pc 2 win 3 iOS 4 android 5 iPad 6 mac
}

type LoginAppleReq struct {
	UserID            string `json:"userID" validate:"required,min=2,max=100" label:"userID"`                       // userID
	IdentityToken     string `json:"identityToken" validate:"required,min=2,max=100" label:"identityToken"`         // identityToken
	AuthorizationCode string `json:"authorizationCode" validate:"required,min=2,max=100" label:"authorizationCode"` // authorizationCode
	DeviceId          string `json:"deviceId" validate:"required,min=10,max=100" label:"设备UUID"`                    // 设备UUID
	AppVersion        string `json:"appVersion" validate:"required,min=1,max=15" label:"app版本"`                     // appVersion
	SystemVersion     string `json:"systemVersion" validate:"required,min=1,max=15" label:"system版本"`               // systemVersion
	Platform          int64  `json:"platform" validate:"required,gte=0,lte=15" label:"登录平台"`                        // 登录平台 1 pc 2 win 3 iOS 4 android 5 iPad 6 mac
}

type LoginResp struct {
	UserId       string `json:"userId"`       // 用户标识
	User         User   `json:"userbase"`     // 用户基本信息
	AccessToken  string `json:"accessToken"`  // 用户token
	AccessExpire int64  `json:"accessExpire"` // 过期时长
}

type WebLoginEmailCodeReq struct {
	Email         string `json:"email" validate:"required,min=2,max=100" label:"邮箱"`                 // 邮箱 2-100
	Code          string `json:"code" validate:"required,min=4,max=6" label:"验证码"`                   // 验证码 4-6
	GoogleCaptcha string `json:"googleCaptcha" validate:"required,min=6,max=2000" label:"谷歌验证Token"` // 谷歌验证Token
	DeviceId      string `json:"deviceId" validate:"required,min=10,max=100" label:"设备UUID"`         // 设备UUID
	BrowserName   string `json:"browserName" validate:"required,min=1,max=30" label:"浏览器名称"`         // browserName
}

type WebLoginEmailPasswordReq struct {
	Email         string `json:"email" validate:"required,min=2,max=100" label:"账号"`                 // 邮箱 2-100
	Password      string `json:"password" validate:"required,min=6,max=32"    label:"密码"`            // 密码 6-32
	GoogleCaptcha string `json:"googleCaptcha" validate:"required,min=6,max=2000" label:"谷歌验证Token"` // 谷歌验证Token
	DeviceId      string `json:"deviceId" validate:"required,min=10,max=100" label:"设备UUID"`         // 设备UUID
	BrowserName   string `json:"browserName" validate:"required,min=1,max=30" label:"浏览器名称"`         // browserName
}

type WebLoginGoogleReq struct {
	Code        string `json:"code" validate:"required,min=2,max=2048" label:"谷歌授权code"`   // 谷歌授权code 2-2048
	CallbackURL string `json:"callbackURL" validate:"required,min=1,max=500" label:"回调路径"` // 回调路径 1-500
	DeviceId    string `json:"deviceId" validate:"required,min=10,max=100" label:"设备UUID"` // 设备UUID 10-100
	BrowserName string `json:"browserName" validate:"required,min=1,max=30" label:"浏览器名称"` // browserName 1-30
}

type WebGoogleAuthReq struct {
	CallbackURL string `json:"callbackURL" validate:"required,min=1,max=200" label:"回调路径"` // 回调路径 1-200
}

type WebLoginResp struct {
	UserId       string `json:"userId"`       // 用户标识
	Email        string `json:"email"`        // 电子邮箱
	Phone        string `json:"phone"`        // 手机号
	PhoneNum     string `json:"phoneNum"`     // 手机号国家区号
	CountryId    int64  `json:"countryId"`    // 国家ID
	Avatar       string `json:"avatar"`       // 头像
	FirstName    string `json:"firstName"`    // 姓
	LastName     string `json:"lastName"`     // 名
	Nickname     string `json:"nickName"`     // 昵称
	AccessToken  string `json:"accessToken"`  // 用户token
	AccessExpire int64  `json:"accessExpire"` // 过期时长
}

type WebGoogleAuthResp struct {
	GoogleUrl   string `json:"url"`         // 域名
	ClientId    string `json:"clientId"`    // id
	RedirectUri string `json:"redirectUri"` // redirect_uri
	Scope       string `json:"scope"`       // scope
	State       string `json:"state"`       // state
}

type WebRegisterEmailReq struct {
	Email          string `json:"email" validate:"required,min=2,max=100" label:"邮箱"`                    // 邮箱 2-100
	Code           string `json:"code" validate:"required,min=4,max=6" label:"验证码"`                      // 验证码 4-6
	Password       string `json:"password" validate:"required,min=6,max=32" label:"密码"`                  // 密码 6-32
	InvitationCode string `json:"invitationCode,optional" validate:"omitempty,min=9,max=10" label:"邀请码"` // 上级邀请码
}

type UpdateUserBaseReq struct {
	FirstName   string `json:"firstName" validate:"required,min=1,max=200" label:"姓"`            // 姓 1-200
	LastName    string `json:"lastName" validate:"required,min=1,max=200" label:"名"`             // 名 1-200
	Birthday    string `json:"birthday" validate:"required,min=1,max=20" label:"生日"`             // 生日 1986-01-01
	CountryId   int64  `json:"countryId" validate:"required,gte=1" label:"国家主键"`                 // 国家主键 >=1
	CountryName string `json:"countryName" validate:"required,min=1,max=200" label:"国家名称"`       // 国家名称 1-200
	Province    string `json:"province,optional" validate:"omitempty,min=0,max=200" label:"省份"`  // 省份 0-200
	City        string `json:"city" validate:"required,min=1,max=200" label:"城市"`                // 城市 1-200
	Address     string `json:"address,optional" validate:"omitempty,min=0,max=500" label:"详细地点"` // 详细地点 0-500
}

type GetOtherUserInfoReq struct {
	UUID string `json:"userId" validate:"required,min=10,max=200" label:"主键"` // 主键
}

type UpdateUserAvatarReq struct {
	Avatar string `json:"avatar" validate:"required,min=1,max=200" label:"头像地址"` // 头像 1-200
}

type UpdateUserPhoneReq struct {
	Code      string `json:"code" validate:"required,min=4,max=6" label:"验证码"`         // 验证码 4-6
	Phone     string `json:"phone" validate:"required,min=4,max=30" label:"手机号"`       // 手机号 4-30
	PhoneNum  string `json:"phoneNum" validate:"required,min=1,max=10" label:"手机国家编号"` // 手机国家编号 1-10
	CountryId int64  `json:"countryId" validate:"required,gte=1" label:"国家主键"`         // 国家主键 >=1
}

type UpdateUserBackgroundReq struct {
	BackgroundImg string `json:"background" validate:"required,min=1,max=200" label:"头像地址"` // 背景 1-200
}

type UpdateUserNameReq struct {
	FirstName string `json:"firstName" validate:"required,min=1,max=200" label:"姓"` // 姓 1-200
	LastName  string `json:"lastName" validate:"required,min=1,max=200" label:"名"`  // 名 1-200
}

type UpdateUserNickNameReq struct {
	Nickname string `json:"nickName" validate:"required,min=1,max=32" label:"昵称"` // 昵称 1-32
}

type UpdateUserBirthdayReq struct {
	Birthday string `json:"birthday" validate:"required,min=1,max=20" label:"生日"` // 生日 1986-01-01
}

type UpdateUserWeightReq struct {
	Height int64 `json:"height" validate:"required,gte=1,lte=500" label:"身高"` // 身高 1-500
	Weight int64 `json:"weight" validate:"required,gte=1,lte=500" label:"体重"` // 体重 1-500
}

type UpdateUserGenderReq struct {
	Gender int64 `json:"gender" validate:"required,gte=0,lte=5" label:"性别"` // 性别 1=女 2=男 3=保密
}

type UpdateUserModeTypeReq struct {
	ModeType int64 `json:"modeType" validate:"required,gte=1,lte=2" label:"是否公开"` // 是否公开 1=公开 2=隐藏
}

type UpdateUserCountryReq struct {
	CountryId   int64  `json:"countryId" validate:"required,gte=1" label:"国家主键"`           // 国家主键 >=1
	CountryName string `json:"countryName" validate:"required,min=1,max=200" label:"国家名称"` // 国家名称 1-200
}

type UpdateUserIdentityReq struct {
	Identity int64 `json:"identity" validate:"required,gte=1" label:"用户身份"` // 用户身份 1=求职者 2=学生 3=招聘方
}

type UpdateUserProvinceReq struct {
	Province string `json:"province" validate:"required,min=1,max=200" label:"省份"` // 省份 1-200
}

type UpdateUserCityReq struct {
	City string `json:"city" validate:"required,min=1,max=200" label:"城市"` // 城市 1-200
}

type UpdateUserAddressReq struct {
	Address string `json:"address" validate:"required,min=1,max=500" label:"详细地点"` // 详细地点 1-500
}

type UpdateUserPurposeCityReq struct {
	PurposeCity string `json:"purposeCity" validate:"required,min=1,max=2000" label:"意向城市"` // 意向城市 1-2000 多个用英语逗号分割
}

type UpdateUserInterestsReq struct {
	Interests string `json:"interests" validate:"required,min=1,max=2000" label:"兴趣爱好"` // 兴趣爱好 1-2000 多个用英语逗号分割
}

type UpdateUserLanguagesReq struct {
	Languages string `json:"languages" validate:"required,min=1,max=2000" label:"兴趣爱好"` // 会的语言 1-2000 多个用英语逗号分割
}

type UpdateUserDatingTargetsReq struct {
	DatingTargets string `json:"datingTargets" validate:"required,min=1,max=2000" label:"交友的目"` // 交友的目 1-2000 多个用英语逗号分割
}

type UpdateUserPersonalStrengthReq struct {
	PersonalStrength string `json:"personalStrength" validate:"required,min=1,max=1000" label:"个人实力"` // 个人实力 1-1000
}

type UpdateUserPersonalSkillsReq struct {
	PersonalSkills string `json:"personalSkills" validate:"required,min=1,max=2000" label:"个人技能"` // 个人技能 1-2000 多个用英语逗号分割
}

type UpdateUserLocationReq struct {
	TimeZone    string  `json:"timeZone" validate:"required,min=0,max=100" label:"时区"`     // 时区 0-100
	Country     string  `json:"country" validate:"required,min=0,max=100" label:"国家"`      // 国家 0-200
	CountryCode string  `json:"countryCode" validate:"required,min=0,max=50" label:"国家编号"` // 国家编号 0-50
	Province    string  `json:"province" validate:"required,min=0,max=200" label:"城市"`     // 省份 0-200
	City        string  `json:"city" validate:"required,min=0,max=200" label:"城市"`         // 城市 0-200
	State       string  `json:"state" validate:"required,min=0,max=200" label:"县"`         // 县 0-200
	Area        string  `json:"area" validate:"required,min=0,max=200" label:"区域"`         // 区域 0-200
	Street      string  `json:"street" validate:"required,min=0,max=500" label:"街道"`       // 街道 0-500
	Latitude    float64 `json:"latitude" validate:"required" label:"纬度"`                   // 纬度
	Longitude   float64 `json:"longitude" validate:"required" label:"经度"`                  // 经度
	PostalCode  string  `json:"postalCode" validate:"required,min=0,max=50" label:"邮政编码"`  // 邮政编码 0-50
	Address     string  `json:"address" validate:"required,min=0,max=1000" label:"详细地点"`   // 详细地点 0-1000
}

type UserFeedbackReq struct {
	Content  string `json:"content" validate:"required,min=10,max=1000" label:"反馈内容"`           // 反馈内容 10-1000字符
	FileUrls string `json:"fileUrls,optional" validate:"omitempty,min=0,max=2000" label:"图片地址"` // 图片地址 多个用逗号分割 0-2000
}

type UserVideo struct {
	Id        int64   `json:"id"`        // 主键
	Title     string  `json:"title"`     // 标题
	CoverUrl  string  `json:"coverUrl"`  // 封面完整地址
	FileUrl   string  `json:"fileUrl"`   // 视频完整地址
	PlayTime  float64 `json:"playTime"`  // 播放时长
	VideoSize float64 `json:"videoSize"` // 视频大小kb
	OrderBy   int64   `json:"orderBy"`   // 排序 从小到大的顺序
}

type AddUserVideo struct {
	Id        int64   `json:"id,optional" validate:"omitempty,gte=0" label:"主键"`             // 主键 0 新增 >0 更新
	Title     string  `json:"title,optional" validate:"omitempty,min=0,max=50" label:"视频标题"` // 视频标题 0-50
	CoverUrl  string  `json:"coverUrl" validate:"required,min=2,max=200" label:"视频封面"`       // 视频封面 2-200
	FileUrl   string  `json:"fileUrl" validate:"required,min=2,max=200" label:"视频URL"`       // 视频URL 2-200
	PlayTime  float64 `json:"playTime" validate:"required,gte=0" label:"播放时长"`               // 播放时长 单位 秒
	VideoSize float64 `json:"videoSize" validate:"required,gte=0" label:"视频大小"`              // 视频大小 单位 kb
	OrderBy   int64   `json:"orderBy,optional" validate:"omitempty,gte=0" label:"视频排序"`      // 视频排序 从小到大的顺序
}

type AddUserVideoReq struct {
	List []AddUserVideo `json:"list" validate:"required" label:"视频集合"` // 视频集合
}

type DeleteUserVideoReq struct {
	Id int64 `json:"id" validate:"required,gte=0" label:"视频id"` // 视频id
}

type UserVideoResp struct {
	List []UserVideo `json:"list"`
}

type UserPhoto struct {
	Id      int64  `json:"id"`      // 主键
	Title   string `json:"title"`   // 标题
	FileUrl string `json:"fileUrl"` // 完整地址
	OrderBy int64  `json:"orderBy"` // 排序 从小到大的顺序
}

type AddUserPhoto struct {
	Id      int64  `json:"id,optional" validate:"omitempty,gte=0" label:"主键"`             // 主键 0 新增 >0 更新
	Title   string `json:"title,optional" validate:"omitempty,min=0,max=50" label:"相册标题"` // 相册标题 0-50
	FileUrl string `json:"fileUrl" validate:"required,min=2,max=200" label:"相册URL"`       // 相册URL 2-200
	OrderBy int64  `json:"orderBy,optional" validate:"omitempty,gte=0" label:"排序"`        // 排序 从小到大的顺序
}

type AddUserPhotoReq struct {
	List []AddUserPhoto `json:"list" validate:"required" label:"相册集合"` // 相册集合
}

type DeleteUserPhotoReq struct {
	Id int64 `json:"id" validate:"required,gte=1" label:"相册id"` // 相册id
}

type UserPhotoResp struct {
	List []UserPhoto `json:"list"`
}

type UserCompany struct {
	Id              int64  `json:"id"`              // 主键
	CompanyName     string `json:"companyName"`     // 工作经验名称
	CompanyCountry  string `json:"companyCountry"`  // 工作经验国家
	CompanyCity     string `json:"companyCity"`     // 工作经验城市
	CompanyIndustry string `json:"companyIndustry"` // 工作经验行业
	StartTime       string `json:"startTime"`       // 开始时间
	EndTime         string `json:"endTime"`         // 结束时间
	JobPosition     string `json:"jobPosition"`     // 工作职位
	JobContent      string `json:"jobContent"`      // 工作内容
	JobSummary      string `json:"jobSummary"`      // 工作总结
	JobSkills       string `json:"jobSkills"`       // 使用技能 多个用英文逗号分隔开
	OrderBy         int64  `json:"orderBy"`         // 排序 从小到大的顺序
}

type AddUserCompanyReq struct {
	Id              int64  `json:"id" validate:"omitempty,gte=0" label:"主键"`                                   // 主键 0 新增 >0 更新
	CompanyName     string `json:"companyName" validate:"required,min=2,max=200" label:"组织名称"`                 // 工作经验名称 2-200
	CompanyCountry  string `json:"companyCountry,optional" validate:"omitempty,min=0,max=100" label:"工作经验国家"`  // 工作经验国家 0-100
	CompanyCity     string `json:"companyCity,optional" validate:"omitempty,min=0,max=100" label:"工作经验城市"`     // 工作经验城市 0-100
	CompanyIndustry string `json:"companyIndustry,optional" validate:"omitempty,min=0,max=100" label:"工作经验行业"` // 工作经验行业 0-100
	StartTime       string `json:"startTime" validate:"required,min=1,max=20" label:"开始时间"`                    // 开始时间 1-20
	EndTime         string `json:"endTime,optional" validate:"omitempty,min=0,max=20" label:"结束时间"`            // 结束时间 0-20
	JobPosition     string `json:"jobPosition" validate:"required,min=1,max=100" label:"工作职位"`                 // 工作职位 1-100
	JobContent      string `json:"jobContent" validate:"required,min=10,max=1000" label:"工作内容"`                // 工作内容 10-1000
	JobSummary      string `json:"jobSummary,optional" validate:"omitempty,min=0,max=1000" label:"工作总结"`       // 工作总结 0-1000
	JobSkills       string `json:"jobSkills,optional" validate:"omitempty,min=0,max=1000" label:"使用技能"`        // 使用技能 0-1000 多个用英文逗号分隔开
	OrderBy         int64  `json:"orderBy" validate:"omitempty,gte=0" label:"排序"`                              // 排序 从小到大的顺序
}

type DeleteUserCompanyReq struct {
	Id int64 `json:"id" validate:"required,gte=0" label:"主键"` // 主键
}

type UpdUserCompanySkillsReq struct {
	Id        int64  `json:"id" validate:"required,gte=0" label:"主键"`                   // 主键
	JobSkills string `json:"jobSkills" validate:"required,min=0,max=1000" label:"使用技能"` // 使用技能 0-1000 多个用英文逗号分隔开
}

type GetUserCompanyReq struct {
	Id int64 `json:"id" validate:"required,gte=0" label:"主键"` // 主键
}

type UserCompanyResp struct {
	List []UserCompany `json:"list"`
}

type UserExperience struct {
	Id                     int64  `json:"id"`           // 主键
	ExperienceOrganization string `json:"organization"` // 所在组织
	ExperiencePosition     string `json:"position"`     // 担任职位
	ExperienceTitle        string `json:"title"`        // 标题
	ExperienceSummary      string `json:"summary"`      // 摘要
	ExperienceContent      string `json:"content"`      // 内容
	StartTime              string `json:"startTime"`    // 入学时间
	EndTime                string `json:"endTime"`      // 毕业时间
	OrderBy                int64  `json:"orderBy"`      // 排序 从小到大的顺序
}

type AddUserExperienceReq struct {
	Id                     int64  `json:"id" validate:"omitempty,gte=0" label:"主键"`                        // 主键 0 新增 >0 更新
	ExperienceOrganization string `json:"organization" validate:"required,min=1,max=100" label:"所在组织"`     // 所在组织 1-100
	ExperiencePosition     string `json:"position" validate:"required,min=1,max=100" label:"担任职位"`         // 担任职位 1-100
	ExperienceTitle        string `json:"title" validate:"required,min=1,max=100" label:"标题"`              // 标题 1-100
	ExperienceSummary      string `json:"summary,optional" validate:"omitempty,min=0,max=200" label:"摘要"`  // 摘要 0-200
	ExperienceContent      string `json:"content" validate:"required,min=1,max=1000" label:"内容"`           // 内容 1-1000
	StartTime              string `json:"startTime" validate:"required,min=1,max=20" label:"开始时间"`         // 开始时间 1-20
	EndTime                string `json:"endTime,optional" validate:"omitempty,min=0,max=20" label:"结束时间"` // 结束时间 0-20
	OrderBy                int64  `json:"orderBy" validate:"omitempty,gte=0" label:"排序"`                   // 排序 从小到大的顺序
}

type DeleteUserExperienceReq struct {
	Id int64 `json:"id" validate:"required,gte=0" label:"主键"` // 主键
}

type GetUserExperienceReq struct {
	Id int64 `json:"id" validate:"required,gte=0" label:"主键"` // 主键
}

type UserExperienceResp struct {
	List []UserExperience `json:"list"`
}

type UserVolunteer struct {
	Id        int64  `json:"id"`        // 主键
	Title     string `json:"title"`     // 标题
	Content   string `json:"content"`   // 内容
	StartTime string `json:"startTime"` // 开始时间
	EndTime   string `json:"endTime"`   // 结束时间
	OrderBy   int64  `json:"orderBy"`   // 视频排序 从小到大的顺序
}

type ChangeUserVolunteerReq struct {
	Id        int64  `json:"id" validate:"omitempty,gte=0" label:"主键"`                        // 主键 0 新增 >0 更新
	Title     string `json:"title" validate:"required,min=1,max=100" label:"标题"`              // 标题 1-100
	Content   string `json:"content" validate:"required,min=1,max=1000" label:"内容"`           // 内容 1-1000
	StartTime string `json:"startTime" validate:"required,min=4,max=20" label:"开始时间"`         // 开始时间 4-20
	EndTime   string `json:"endTime,optional" validate:"omitempty,min=0,max=20" label:"结束时间"` // 结束时间 0-20
	OrderBy   int64  `json:"orderBy" validate:"omitempty,gte=0" label:"排序"`                   // 排序 从小到大的顺序
}

type DeleteUserVolunteerReq struct {
	Id int64 `json:"id" validate:"required,gte=0" label:"志愿者属性id"` // 志愿者属性id
}

type GetUserVolunteerReq struct {
	Id int64 `json:"id" validate:"required,gte=0" label:"志愿者属性id"` // 志愿者属性id
}

type UserVolunteerResp struct {
	List []UserVolunteer `json:"list"`
}

type UserProject struct {
	Id                  int64  `json:"id"`                  // 主键
	ProjectName         string `json:"projectName"`         // 项目经验名称
	ProjectContent      string `json:"projectContent"`      // 项目经验内容
	JobPosition         string `json:"jobPosition"`         // 工作职位
	JobContent          string `json:"jobContent"`          // 工作内容
	StartTime           string `json:"startTime"`           // 开始时间
	EndTime             string `json:"endTime"`             // 结束时间
	ProjectLinkPlatform string `json:"projectLinkPlatform"` // 链接名称
	ProjectLink         string `json:"projectLink"`         // 项目经验链接
	ProjectSkills       string `json:"projectSkills"`       // 使用技能 多个用英文逗号分隔开
	OrderBy             int64  `json:"orderBy"`             // 排序 从小到大的顺序
}

type AddUserProjectReq struct {
	Id                  int64  `json:"id" validate:"omitempty,gte=0" label:"主键"`                                    // 主键 0 新增 >0 更新
	ProjectName         string `json:"projectName" validate:"required,min=1,max=100" label:"项目经验名称"`                // 项目经验名称 1-100
	ProjectContent      string `json:"projectContent" validate:"required,min=1,max=1000" label:"项目经验内容"`            // 项目经验内容 1-1000
	JobPosition         string `json:"jobPosition,optional" validate:"omitempty,min=0,max=100" label:"工作职位"`        // 工作职位 0-100
	JobContent          string `json:"jobContent,optional" validate:"omitempty,min=0,max=1000" label:"工作内容"`        // 工作内容 0-1000
	StartTime           string `json:"startTime" validate:"required,min=1,max=20" label:"开始时间"`                     // 开始时间 1-20
	EndTime             string `json:"endTime,optional" validate:"omitempty,min=0,max=20" label:"结束时间"`             // 结束时间 0-20
	ProjectLinkPlatform string `json:"projectLinkPlatform,optional" validate:"omitempty,min=0,max=30" label:"链接名称"` // 链接名称 0-30
	ProjectLink         string `json:"projectLink,optional" validate:"omitempty,min=0,max=500" label:"项目经验链接"`      // 项目经验链接 0-500
	ProjectSkills       string `json:"projectSkills,optional" validate:"omitempty,min=0,max=1000" label:"使用技能"`     // 使用技能 0-1000 多个用英文逗号分隔开
	OrderBy             int64  `json:"orderBy,optional" validate:"omitempty,gte=0" label:"排序"`                      // 排序 从小到大的顺序
}

type DeleteUserProjectReq struct {
	Id int64 `json:"id" validate:"required,gte=0" label:"主键"` // 主键
}

type UpdUserProjectSkillsReq struct {
	Id            int64  `json:"id" validate:"required,gte=0" label:"主键"`                        // 主键
	ProjectSkills string `json:"projectSkills" validate:"omitempty,min=0,max=1000" label:"使用技能"` // 使用技能 0-1000 多个用英文逗号分隔开
}

type GetUserProjectReq struct {
	Id int64 `json:"id" validate:"required,gte=0" label:"主键"` // 主键
}

type UserProjectResp struct {
	List []UserProject `json:"list"`
}

type UserEducation struct {
	Id               int64  `json:"id"`        // 主键
	OrganizationName string `json:"name"`      // 学校或组织名称
	StartTime        string `json:"startTime"` // 开始时间
	EndTime          string `json:"endTime"`   // 结束时间
	StudyAchievement string `json:"content"`   // 教育内容
	OrderBy          int64  `json:"orderBy"`   // 排序 从小到大的顺序
}

type AddUserEducationReq struct {
	Id               int64  `json:"id" validate:"omitempty,gte=0" label:"主键"`                        // 主键 0 新增 >0 更新
	OrganizationName string `json:"name" validate:"required,min=1,max=100" label:"组织名称"`             // 学校或组织名称 1-100
	StartTime        string `json:"startTime" validate:"required,min=1,max=20" label:"入职时间"`         // 开始时间 1-20
	EndTime          string `json:"endTime,optional" validate:"omitempty,min=0,max=20" label:"离职时间"` // 结束时间 0-20
	StudyAchievement string `json:"content" validate:"required,min=1,max=500" label:"教育内容"`          // 教育内容 1-500
	OrderBy          int64  `json:"orderBy,optional" validate:"omitempty,gte=0" label:"排序"`          // 排序 从小到大的顺序
}

type DeleteUserEducationReq struct {
	Id int64 `json:"id" validate:"required,gte=0" label:"主键"` // 主键
}

type GetUserEducationReq struct {
	Id int64 `json:"id" validate:"required,gte=0" label:"主键"` // 主键
}

type UserEducationResp struct {
	List []UserEducation `json:"list"`
}

type UserCustomAttribute struct {
	Id        int64  `json:"id"`        // 主键
	Title     string `json:"title"`     // 标题 3-20
	Content   string `json:"content"`   // 内容
	Summary   string `json:"summary"`   // 摘要
	StartTime string `json:"startTime"` // 开始时间
	EndTime   string `json:"endTime"`   // 结束时间
	OrderBy   int64  `json:"orderBy"`   // 视频排序 从小到大的顺序
}

type ChangeUserCustomAttributeReq struct {
	Id        int64  `json:"id" validate:"omitempty,gte=0" label:"主键"`                        // 主键 0 新增 >0 更新
	Title     string `json:"title" validate:"required,min=3,max=30" label:"标题"`               // 标题 3-30
	Content   string `json:"content" validate:"required,min=5,max=1000" label:"内容"`           // 内容 5-1000
	Summary   string `json:"summary,optional" validate:"omitempty,min=0,max=200" label:"摘要"`  // 摘要 0-200
	StartTime string `json:"startTime" validate:"required,min=4,max=20" label:"开始时间"`         // 开始时间 4-20
	EndTime   string `json:"endTime,optional" validate:"omitempty,min=0,max=20" label:"结束时间"` // 结束时间 0-20
	OrderBy   int64  `json:"orderBy" validate:"omitempty,gte=0" label:"排序"`                   // 排序 从小到大的顺序
}

type DeleteUserCustomAttributeReq struct {
	Id int64 `json:"id" validate:"required,gte=0" label:"自定义属性id"` // 自定义属性id
}

type GetUserCustomAttributeReq struct {
	Id int64 `json:"id" validate:"required,gte=0" label:"自定义属性id"` // 自定义属性id
}

type UserCustomAttributeResp struct {
	List []UserCustomAttribute `json:"list"`
}
