SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

--
-- 数据库： `app_share_cv`
--

CREATE DATABASE IF NOT EXISTS app_share_cv DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_general_ci;
use app_share_cv;

-- app国家表
DROP TABLE IF EXISTS `app_country`;
CREATE TABLE `app_country`
(
    `id`                bigint       NOT NULL COMMENT '编号' AUTO_INCREMENT,
    `num`               varchar(10)  NOT NULL DEFAULT '' COMMENT '国家区号',
    `code`              varchar(10)  NOT NULL DEFAULT '' COMMENT '国家图标',
    `name`              varchar(200) NOT NULL DEFAULT '' COMMENT '国家英文名称',
    `name_cn`           varchar(200) NOT NULL DEFAULT '' COMMENT '国家中文名称',
    `create_at`         timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_at`         timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted_at`        timestamp             DEFAULT NULL COMMENT '删除时间',
    PRIMARY KEY (`id`),
    KEY        `idx_code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='app国家表';

INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('阿富汗','Afghanistan','AF','93');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('奥兰群岛','Aland Islands','AX','358');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('阿尔巴尼亚','Albania','AL','355');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('阿尔及利亚','Algeria','DZ','213');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('美属萨摩亚','American Samoa','AS','1');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('安道尔','Andorra','AD','376');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('安哥拉','Angola','AO','244');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('安圭拉','Anguilla','AI','1264');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('南极洲','Antarctica','AQ','672');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('安提瓜和巴布达','Antigua and Barbuda','AG','1268');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('阿根廷','Argentina','AR','54');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('亚美尼亚','Armenia','AM','374');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('阿鲁巴','Aruba','AW','297');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('阿森松','Ascension','AC','247');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('澳大利亚','Australia','AU','61');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('奥地利','Austria','AT','43');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('阿塞拜疆','Azerbaijan','AZ','994');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('巴哈马','Bahamas','BS','1242');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('巴林','Bahrain','BH','973');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('孟加拉','Bangladesh','BD','880');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('巴巴多斯','Barbados','BB','1246');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('白俄罗斯','Belarus','BY','375');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('比利时','Belgium','BE','32');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('伯利兹','Belize','BZ','501');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('贝宁','Benin','BJ','229');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('百慕大','Bermuda','BM','1441');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('不丹','Bhutan','BT','975');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('玻利维亚','Bolivia','BO','591');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('博奈尔','Bonaire','BQ','599');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('波斯尼亚和黑塞哥维那','Bosnia and Herzegovina','BA','387');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('博茨瓦纳','Botswana','BW','267');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('巴西','Brazil','BR','55');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('英属印度洋领地','British Indian Ocean Territory','IO','246');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('文莱','Brunei','BN','673');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('保加利亚','Bulgaria','BG','359');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('布基纳法索','Burkina Faso','BF','226');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('布隆迪','Burundi','BI','257');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('佛得角','Cabo Verde','CV','238');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('柬埔寨','Cambodia','KH','855');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('喀麦隆','Cameroon','CM','237');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('加拿大','Canada','CA','1');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('开曼群岛','Cayman Islands','KY','1');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('中非','Central African Republic','CF','236');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('乍得','Chad','TD','235');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('智利','Chile','CL','56');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('中国','China','CN','86');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('圣诞岛','Christmas Islands','CX','61');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('科科斯（基林）群岛','Cocos (keeling) Islands','CC','61');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('哥伦比亚','Colombia','CO','57');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('科摩罗','Comoros','KM','269');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('刚果（金）','Congo (Congo-Kinshasa)','CD','243');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('刚果','Congo','CG','242');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('库克群岛','Cook Islands','CK','682');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('哥斯达黎加','Costa Rica','CR','506');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('科特迪瓦','Cote D’Ivoire','CI','225');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('克罗地亚','Croatia','HR','385');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('古巴','Cuba','CU','53');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('塞浦路斯','Curaçao','CW','599');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('库拉索','Cyprus','CY','357');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('捷克','Czech','CZ','420');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('丹麦','Denmark','DK','45');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('吉布提','Djibouti','DJ','253');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('多米尼加','Dominica','DM','1');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('多米尼加共和国','Dominican Republic','DO','1');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('厄瓜多尔','Ecuador','EC','593');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('埃及','Egypt','EG','20');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('萨尔瓦多','El Salvador','SV','503');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('赤道几内亚','Equatorial Guinea','GQ','240');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('厄立特里亚','Eritrea','ER','291');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('爱沙尼亚','Estonia','EE','372');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('斯威士兰','Eswatini','SZ','268');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('埃塞俄比亚','Ethiopia','ET','251');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('福克兰群岛/马尔维纳斯群岛','Falkland Islands/Malvinas','FK','500');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('法罗群岛','Faroe Islands','FO','298');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('斐济','Fiji','FJ','679');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('芬兰','Finland','FI','358');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('法国','France','FR','33');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('法属圭亚那','French Guiana','GF','594');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('法属波利尼西亚','French Polynesia','PF','689');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('法属南部和南极领地','French Southern Territorie','TF','262');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('加蓬','Gabon','GA','241');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('冈比亚','Gambia','GM','220');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('格鲁吉亚','Georgia','GE','995');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('德国','Germany','DE','49');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('加纳','Ghana','GH','233');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('直布罗陀','Gibraltar','GI','350');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('希腊','Greece','GR','30');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('格陵兰岛','Greenland','GL','299');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('格林纳达','Grenada','GD','1809');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('瓜德罗普岛','Guadeloupe','GP','590');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('关岛','Guam','GU','1671');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('危地马拉','Guatemala','GT','502');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('根西岛','Guernsey','GG','44');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('几内亚','Guinea','GN','224');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('几内亚比绍','Guinea-Bissau','GW','245');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('圭亚那','Guyana','GY','592');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('海地','Haiti','HT','509');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('赫德岛和麦克唐纳群岛','Heard Island and McDonald Islands','HM','672');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('梵蒂冈','Vatican City','VA','379');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('洪都拉斯','Honduras','HN','504');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('香港','Hong Kong','HK','852');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('匈牙利','Hungary','HU','36');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('冰岛','Iceland','IS','354');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('印度','India','IN','91');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('印度尼西亚','Indonesia','ID','62');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('伊朗','Iran','IR','98');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('伊拉克','Iraq','IQ','964');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('爱尔兰','Ireland','IE','353');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('马恩岛','Isle of Man','IM','44');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('以色列','Israel','IL','972');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('意大利','Italy','IT','39');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('牙买加','Jamaica','JM','1876');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('日本','Japan','JP','81');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('泽西岛','Jersey','JE','44');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('约旦','Jordan','JO','962');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('哈萨克斯坦','Kazakhstan','KZ','327');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('肯尼亚','Kenya','KE','254');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('基里巴斯','Kiribati','KI','686');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('朝鲜','Korea (North)','KP','850');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('韩国','Korea (South)','KR','82');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('科威特','Kuwait','KW','965');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('吉尔吉斯斯坦','Kyrgyzstan','KG','331');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('老挝','Laos','LO','856');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('拉脱维亚','Latvia','LV','371');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('黎巴嫩','Lebanon','LB','961');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('莱索托','Lesotho','LS','266');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('利比里亚','Liberia','LR','231');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('利比亚','Libya','LY','218');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('列支敦士登','Liechtenstein','LI','423');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('立陶宛','Lithuania','LT','370');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('卢森堡','Luxembourg','LU','352');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('澳门','Macao','MO','853');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('北马其顿','North Macedonia','MK','389');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('马达加斯加','Madagascar','MG','261');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('马拉维','Malawi','MW','265');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('马来西亚','Malaysia','MY','60');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('马尔代夫','Maldives','MV','960');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('马里','Mali','ML','223');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('马耳他','Malta','MT','356');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('马绍尔群岛','Marshall Islands','MH','692');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('马提尼克岛','Martinique','MQ','596');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('毛里塔尼亚','Mauritania','MR','222');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('毛里求斯','Mauritius','MU','230');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('马约特','Mayotte','YT','262');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('墨西哥','Mexico','MX','52');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('密克罗尼西亚','Micronesia','MF','691');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('摩尔多瓦','Moldova','MD','373');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('摩纳哥','Monaco','MC','377');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('蒙古','Mongolia','MN','976');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('黑山','Montenegro','ME','382');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('蒙特塞拉特','Montserrat','MS','1664');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('摩洛哥','Morocco','MA','212');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('莫桑比克','Mozambique','MZ','258');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('缅甸','Myanmar','MM','95');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('纳米比亚','Namibia','NA','264');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('瑙鲁','Nauru','NR','674');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('尼泊尔','Nepal','NP','977');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('荷兰','Netherlands','NL','31');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('新喀里多尼亚','New Caledonia','NC','687');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('新西兰','New Zealand','NZ','64');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('尼加拉瓜','Nicaragua','NI','505');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('尼日尔','Niger','NE','227');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('尼日利亚','Nigeria','NG','234');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('纽埃','Niue','NU','683');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('诺福克岛','Norfolk Island','NF','672');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('北马里亚纳群岛','Northern Mariana Islands','MP','1670');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('挪威','Norway','NO','47');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('阿曼','Oman','OM','968');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('巴基斯坦','Pakistan','PK','92');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('帕劳','Palau','PW','680');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('巴勒斯坦','Palestine','PS','970');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('巴拿马','Panama','PA','507');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('巴布亚新几内亚','Papua New Guinea','PG','675');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('巴拉圭','Paraguay','PY','595');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('秘鲁','Peru','PE','51');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('菲律宾','Philippines','PH','63');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('皮特凯恩群岛','Pitcairn Islands','PN','64');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('波兰','Poland','PL','48');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('葡萄牙','Portugal','PT','351');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('波多黎各','Puerto Rico','PR','1787');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('卡塔尔','Qatar','QA','974');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('留尼汪岛','Reunion','RE','262');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('罗马尼亚','Romania','RO','40');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('俄罗斯联邦','Russian Federation','RU','7');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('卢旺达','Rwanda','RW','250');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('圣巴泰勒米岛','Saint Barthélemy','BL','590');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('圣赫勒拿','Saint Helena','SH','290');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('圣基茨和尼维斯','Saint Kitts-Nevis','KN','1');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('圣卢西亚','Saint Lucia','LC','1758');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('圣马丁岛','Saint Martin','MF','599');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('圣皮埃尔和密克隆','Saint Pierre and Miquelon','PM','508');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('圣文森特和格林纳丁斯','Saint Vincent and the Grenadines','VG','1784');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('萨摩亚','Samoa','WS','685');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('圣马力诺','San Marino','SM','378');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('圣多美和普林西比','Sao Tome and Principe','ST','239');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('沙特阿拉伯','Saudi Arabia','SA','966');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('塞内加尔','Senegal','SN','221');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('塞尔维亚','Serbia','RS','381');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('塞舌尔','Seychelles','SC','248');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('塞拉利昂','Sierra Leone','SL','232');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('新加坡','Singapore','SG','65');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('圣馬丁','Sint Maarten','SX','599');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('斯洛伐克','Slovakia','SK','421');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('斯洛文尼亚','Slovenia','SI','386');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('所罗门群岛','Solomon Islands','SB','677');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('索马里','Somalia','SO','252');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('南非','South Africa','ZA','27');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('南乔治亚岛和南桑威奇群岛','South Georgia and the South Sandwich Islands','GS','500');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('南苏丹','South Sudan','SS','211');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('西班牙','Spain','ES','34');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('斯里兰卡','Sri Lanka','LK','94');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('苏丹','Sudan','SD','249');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('苏里南','Suriname','SR','597');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('斯瓦尔巴','Svalbard','SJ','47');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('斯威士兰','Swaziland','SZ','268');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('瑞典','Sweden','SE','46');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('瑞士','Switzerland','CH','41');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('叙利亚','Syria','SY','963');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('台湾','Taiwan','TW','886');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('塔吉克斯坦','Tajikistan','TJ','992');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('坦桑尼亚','Tanzania','TZ','255');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('泰国','Thailand','TH','66');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('东帝汶','Timor-Leste','TL','670');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('多哥','Togo','TG','228');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('托克劳','Tokelau','TK','690');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('汤加','Tonga','TO','676');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('特立尼达和多巴哥','Trinidad and Tobago','TT','1809');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('突尼斯','Tunisia','TN','216');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('土耳其','Turkey','TR','90');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('土库曼斯坦','Turkmenistan','TM','993');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('特克斯和凯科斯群岛','Turks and Caicos Islands','TC','1');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('图瓦卢','Tuvalu','TV','688');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('乌干达','Uganda','UG','256');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('乌克兰','Ukraine','UA','380');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('阿拉伯联合酋长国','United Arab Emirates','AE','971');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('英国','United Kingdom','UK','44');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('美国本土外小岛屿','United States Minor Outlying Islands','UM','1');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('美国','United States','US','1');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('乌拉圭','Uruguay','UY','598');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('乌兹别克斯坦','Uzbekistan','UZ','233');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('瓦努阿图','Vanuatu','VU','678');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('委内瑞拉','Venezuela','VE','58');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('越南','Vietnam','VN','84');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('英属维尔京群岛','Virgin Islands (British)','VG','1');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('美属维尔京群岛','Virgin Islands (U.S.)','VI','1');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('瓦利斯群岛和富图纳群岛','Wallis and Futuna','WF','681');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('西撒哈拉','Western Sahara','EH','212');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('也门','Yemen','YE','967');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('赞比亚','Zambia','ZM','260');
INSERT INTO `app_country` (`name_cn`,`name`,`code`,`num`)  VALUE('津巴布韦','Zimbabwe','ZW','263');

