export default {
    "Email": "Email",
    "Password": "Password",
    "ForgotPassword": "Forgot Password?",
    "Signin": "Sign in",
    "or": "or",
    "Sign in with Google": "Sign in with Google",
    "title": "<div>Welcome to the </div><div>share resume community</div>",

    "Module": "The perfect module to make your talent everywhere.",
    "Modules": "Modules",
    "Languages": "Languages",
    "Skills": "Skills",
    "Photos": "Photos",
    "Passions": "Passions",
    "Summary": "Summary",
    "Strengths": "Strengths",
    "Experience": "Experience",
    "Projects": "Projects",
    "TrainingCourses": "Training/Courses",
    "Industry": "Industry",
    "Expertise": "Expertise",
    "Education": "Education",
    "Custom": "Custom",

    "ShareGoalsTip": "Join us, find what you want, meet what you meet",
    "ShareGoals": "Share goals",
    "Favorite person": "Favorite person",
    "Looking for a job": "Looking for a job",
    "Find a partner": "Find a partner",
    "Find a founder": "Find a founder",
    "Find someone to travel with": "Find someone to travel with",
    "Find someone to climb the mountain together": "Find someone to climb the mountain together",
    "Chat with someone": "Chat with someone",
    "Find appointments": "Find appointments",
    "Find social activities": "Find social activities",
    "To be recognized by someone": "To be recognized by someone",
    "Leave behind talent": "Leave behind talent",

    "Share": "Share your resume and let more people get to know you.",
    "Share resume": "Share Resume",

    "ShareTitle": "A unique resume will provide you with different job opportunities and social connections.",
    "ShareContent": "Don't you believe that a resume is more than just a piece of paper? It is a way of communicating with people who don't know you yet. Let's start a new world by making a complete resume.",

    "Please enter a valid email addre": "Please enter a valid email address",
    "Password must be 6 characters or more": "Password must be 6 characters or more.",

}