export default {
    "Deleting custom attributes succeeded": "Deleting custom attributes succeeded",
    "Added to custom attribute successfully": "Added to custom attribute successfully",
    "OK to delete custom title": "OK to delete custom title?",
    "hint": "Delete",
    "confirm": "confirm",
    "Cancel": "Cancel",
    "Skill added successfully": "Skill added successfully",
    "Skill deleted successfully": "Skill deleted successfully",
    "Confirm delete skill": "Confirm delete skill?",
    "skills need to keep one": "skills need to keep one",
    "Confirm to delete interest": "Confirm to delete interest？",
    "Interest needs to keep one": "Interest needs to keep one",
    "Determining the ideal target for removal": "Determining the ideal target for removal?",
    "Deletion of ideal target succeeded": "Deletion of ideal target succeeded",
    "Destination city added successfully": "Destination city added successfully",
    "The ideal goal requires retaining a": "The ideal goal requires retaining a",
    "Determine the destination city for deletion": "Determine the destination city for deletion?",
    "Destination city retains at least one": "Destination city retains at least one",
    "increase personal strength success": "increase personal strength success",
    "Modify personal strength successfully": "iModify personal strength successfully",
    "Add Company Experience Success": "Add Company Experience Success",
    "Modify Company Experience Success": "Modify Company Experience Success",
    "Whether to delete company skills": "Whether to delete company skills?",
    "Update personal information successfully": "Update personal information successfully",

    "Added successfully":'Added successfully',
    "Deleted successfully":'Deleted successfully',
    "Edited successfully":'Edited successfully',
    "Upload failed":'Upload failed',
    "Uploaded successfully":'Uploaded successfully',
    "Failed to add":'Failed to add',
    "Failed to delete":'Failed to delete',
    "Failed to edit":'Failed to edit',
    "At least keep one":'At least keep one',
    "Incorrect verification code":'Incorrect verification code',

    "image type":" The image type must be one of GIF, JPEG, JPG, PNG, BMP.",
}