export default {
    "Email": "Email",
    "Password": "Password",
    "Please enter a valid email address": "Please enter a valid email address",
    "E-mail format is incorrect": "E-mail format is incorrect",
    "6 digits or more": "Password must be 6 characters or more.",
    "ForgotPassword": "ForgotPassword?",
    "please enter password": "Password must be 6 characters or more.",
    "agree and join": "By clicking Agree & Join, you agree to the Share",
    "agree and join02": "Privacy Policy,",
    "agree and join03": "User Agreement, ",
    "Agree & Join": "Agree & Join",
    "User Services Agreement": "User Services Agreement",
    "Privacy Agreement": "Privacy Agreementt",
    "and": "and",
    "policy": "policy.",
    "Signin": "Sign in",
    "Already on Realme": "Already on Share CV",
    "or": "or",
    "Sign in with Google": "Sign in with Google",
    "Name": "Frist Name",
    "please enter a name": "please enter a name",
    "surname": "Last Name",
    "Please enter a last name": "Please enter a last name",
    "continue": "Continue",
    "full name": "Full name",
    "Please enter full name": "Please enter full name",
    "Nick name": "Nick name",
    "Please enter a nickname": "Please enter a nickname",
    "welcome": "Welcome",
    "fill in a profile": "Let's start your profile, connect to people you know, and engage with them on topics you care about.",
    "Confirm your email": "Confirm your email",
    "send code": "send code",
    "are you looking for a new job": "are you looking for a new job?",
    "Get the most out of your career": "Get the most out of your career",
    "personal information": "Your profile helps you discover new contacts and opportunities",
    "personal search": "We can help you prepare for your search. Your answer is personal.",
    "find a job": "What kind of Job are you looking for? ",
    "label position": "You can choose up to 5 titles and locations.",
    "country region": "Country/Region",
    "Please enter a country": "United States",
    "Country/Region": "Country/Region",
    "Address": "Address",
    "Please enter detailed address": "Menlo Park, California",
    "most recent job": "most recent job",
    "Please enter a recent job title": "Please enter a recent job title",
    "employment type": "employment type",
    "Please enter employment type": "Please enter employment type",
    "nearest company": "nearest company",
    "Please enter the nearest company": "Please enter the nearest company",
    "university/school": "university/school",
    "Please enter university/school": "Please enter university/school",
    "Starting time": "Starting time",
    "Please enter a start time": "Please enter a start time",
    "结束时间": "结束时间02",
    "请输入结束时间": "请输入结束时间02",
    "我不是学生": "我不是学生02",
    "我是学生": "我是学生02",
    "确定": "确定02",
    "yes": "Yes",
    "not now": "not now",
    "职务名称": "职务名称02",
    "工作地点": "工作地点02",
    "请输入职务名称": "请输入职务名称02",
    "请输入工作地点": "请输入工作地点02",
    "Your privacy is important": "Your privacy is important",
    "promotional information01": "We may send you member updates, recruiter messages, job",
    "promotional information011": "suggestions, invitations, reminders and promotional messages",
    "promotional information012": "from us and our partners. You can change your",
    "promotional information02": "preferences",
    "promotional information03": "anytime.",
    "Didnt receive the code": "Didn't receive the code?",
    "Send again": "Send again",
    "Agree & Confirm": "Agree & Confirm",
    "title01": "Make the most of your profession life",
    "Name updated successfully": "Name updated successfully",
    "set location success": "set location success",
    "update country success": "update country success",

    'password prompt twice': "in English is lease make sure the two passwords match and are at least 6 characters long.",
}