export default {
    "Email": "邮箱",
    "Password": "密码",
    "ForgotPassword": "忘记密码?",
    "Signin": "登录",
    "or": "or",
    "Sign in with Google": "谷歌登录",
    "title": "<div>Welcome to the </div><div>share resume community</div>",

    "Module": "完善的模块，让你的才华无处不在.",
    "Modules": "模块",
    "Languages": "语言",
    "Skills": "技能",
    "Photos": "照片",
    "Passions": "激情",
    "Summary": "总结",
    "Strengths": "优势",
    "Experience": "经验",
    "Projects": "项目",
    "TrainingCourses": "培训/课程",
    "Industry": "行业",
    "Expertise": "专业知识",
    "Education": "教育",
    "Custom": "自定义",

    "ShareGoalsTip": "加入我们，找你所想，遇你所遇",
    "ShareGoals": "分享目的",
    "Favorite person": "喜欢的人",
    "Looking for a job": "寻找一份工作",
    "Find a partner":  "找一个搭档",
    "Find a founder": "找一位创始人",
    "Find someone to travel with": "找一个人一起旅行",
    "Find someone to climb the mountain together": "找人一起爬山",
    "Chat with someone": "找人聊天",
    "Find appointments": "寻找约会对象",
    "Find social activities": "寻找社交活动",
    "To be recognized by someone": "被人认识",
    "Leave behind talent": "留下印象",

    "Share":  "制作免费简历，让更多人方便的结交你.",
    "Share resume": "免费制作简历",

    "ShareTitle": "一份独特的简历，会为你提供不一样的工作机会和社交关系.",
    "ShareContent": "简历它不仅仅是一张纸，你不相信吗？它是你与世界不认识你的人的交流方式，制作一份完整的简历，让我们开启人生新的世界吧",

    "Please enter a valid email addre": "Please enter a valid email address",
}