export default {
    "Deleting custom attributes succeeded": "删除自定义属性成功",
    "Added to custom attribute successfully": "添加自定义属性成功",
    "OK to delete custom title": "确定删除自定义标题?",
    "hint": "提示",
    "confirm": "确认",
    "Cancel": "取消",
    "Skill added successfully": "添加技能成功",
    "Skill deleted successfully": "删除技能成功",
    "Confirm delete skill": "确定删除技能?",
    "skills need to keep one": "技能需要保留一个",
    "Confirm to delete interest": "确定删除兴趣？",
    "Interest needs to keep one": "兴趣需要保留一个",
    "Determining the ideal target for removal": "确定删除理想的目标?",
    "Deletion of ideal target succeeded": "删除理想目标成功",
    "Destination city added successfully": "目的地城市添加成功",
    "The ideal goal requires retaining a": "理想的目标需要保留一个",
    "Determine the destination city for deletion": "确定删除目的城市?",
    "Destination city retains at least one": "目的城市至少保留一个",
    "increase personal strength success": "增加个人实力成功",
    "Modify personal strength successfully": "修改个人实力成功",
    "Add Company Experience Success": "添加公司经历成功",
    "Modify Company Experience Success": "修改公司经历成功",
    "Whether to delete company skills": "是否删除公司技能?",
    "Update personal information successfully": "更新个人信息成功",

    "Added successfully":'添加成功',
    "Deleted successfully":'删除成功',
    "Edited successfully":'编辑成功',
    "Upload failed":'上传失败',
    "Uploaded successfully":'上传成功',
    "Failed to add":'添加失败',
    "Failed to delete":'删除失败',
    "Failed to edit":'编辑失败',
    "At least keep one":'至少留一个',
    "Incorrect verification code":'验证码错误',

    "image type":"图片类型必须是.gif,jpeg,jpg,png,bmp中的一种"
}