export default {
    "Email": "邮箱",
    "Password": "密码",
    "Please enter a valid email address": "请输入邮箱",
    "E-mail format is incorrect": "邮箱格式不正确",
    "6 digits or more": "6位数以上",
    "ForgotPassword": "忘记密码?",
    "please enter password": "请输入密码",
    "agree and join": "同意并加入",
    "agree and join02": "隐私协议",
    "agree and join03": "用户服务协议、",
    "Agree & Join": "同意并加入",
    "and": "和",
    "policy": "政策。",
    "Signin": "登录",
    "Already on Realme": "已经在分享简历了",
    "or": "or",
    "Sign in with Google": "谷歌登录",
    "Name": "名字",
    "please enter a name": "请输入名字",
    "surname": "姓",
    "Please enter a last name": "请输入姓",
    "continue": "继续",
    "full name": "全名",
    "Please enter full name": "请输入全名",
    "Nick name": "昵称",
    "Please enter a nickname": "请输入昵称",
    "welcome": "欢迎",
    "fill in a profile": "让我们开始您的个人资料，联系您认识的人，并与他们谈论你关心的话题。",
    "Confirm your email": "确认您的电子邮件",
    "send code": "发送代码",
    "are you looking for a new job": "你在找新工作吗?",
    "Get the most out of your career": "充分利用职业生涯",
    "personal information": "您的个人资料可帮助您发现新的联系人和机会",
    "personal search": "我们可以帮助您准备搜索。你的回答是私人的。",
    "find a job": "你想找什么样的工作?",
    "label position": "您最多可以选择5个标题和位置。",
    "country region": "国家/地区",
    "Please enter a country": "请输入国家/地区",
    "Address": "详细地址",
    "Please enter detailed address": "请输入详细地址",
    "most recent job": "最近的职务",
    "Please enter a recent job title": "请输入最近的职务",
    "employment type": "就业类型",
    "Please enter employment type": "请输入就业类型",
    "nearest company": "最近的公司",
    "Please enter the nearest company": "请输入最近的公司",
    "university/school": "大学/学校",
    "Please enter university/school": "请输入大学/学校",
    "Starting time": "开始时间",
    "Please enter a start time": "请输入开始时间",
    "结束时间": "结束时间",
    "请输入结束时间": "请输入结束时间",
    "我不是学生": "我不是学生",
    "我是学生": "我是学生",
    "确定": "确定",
    "yes": "是的",
    "not now": "不是现在",
    "职务名称": "职务名称",
    "工作地点": "工作地点",
    "请输入职务名称": "请输入职务名称",
    "请输入工作地点": "请输入工作地点",
    "Your privacy is important": "你的隐私很重要",
    // "promotional information": "我们可能会向您发送会员更新、招聘人员信息、工作建议、邀请、提醒以及我们和合作伙伴的促销信息。您可以随时更改偏好。",
    "promotional information01": "We may send you member updates, recruiter messages, job " +
        "suggestions, invitations, reminders and promotional messages from us and our " +
        "partners. You can change your ",
    "promotional information02": "preferences",
    "promotional information03": "anytime.",
    "Didnt receive the code": "没有收到代码？",
    "Send again": "再次发送",
    "Agree & Confirm": "同意并确认",
    "title01": "充分利用你的职业生涯",
    "Name updated successfully": "更新姓名成功",
    "set location success": "更新详情地址成功",
    "update country success": "更新国家成功",

    'password prompt twice': "两次密码请保持一致并大于等于6位数",

}