// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	appUserVolunteerFieldNames          = builder.RawFieldNames(&AppUserVolunteer{})
	appUserVolunteerRows                = strings.Join(appUserVolunteerFieldNames, ",")
	appUserVolunteerRowsExpectAutoSet   = strings.Join(stringx.Remove(appUserVolunteerFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	appUserVolunteerRowsWithPlaceHolder = strings.Join(stringx.Remove(appUserVolunteerFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAppUserVolunteerIdPrefix = "cache:appUserVolunteer:id:"
)

type (
	appUserVolunteerModel interface {
		Insert(ctx context.Context, data *AppUserVolunteer) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AppUserVolunteer, error)
		Update(ctx context.Context, data *AppUserVolunteer) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAppUserVolunteerModel struct {
		sqlc.CachedConn
		table string
	}

	AppUserVolunteer struct {
		Id        int64        `db:"id"`         // 编号
		UserId    int64        `db:"user_id"`    // 用户id
		Title     string       `db:"title"`      // 志愿者标题
		Content   string       `db:"content"`    // 志愿者内容
		StartTime string       `db:"start_time"` // 开始时间
		EndTime   string       `db:"end_time"`   // 结束时间
		OrderBy   int64        `db:"order_by"`   // 排序从小到大
		CreateAt  time.Time    `db:"create_at"`  // 创建时间
		UpdateAt  time.Time    `db:"update_at"`  // 更新时间
		DeletedAt sql.NullTime `db:"deleted_at"` // 删除时间
	}
)

func newAppUserVolunteerModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAppUserVolunteerModel {
	return &defaultAppUserVolunteerModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`app_user_volunteer`",
	}
}

func (m *defaultAppUserVolunteerModel) Delete(ctx context.Context, id int64) error {
	appUserVolunteerIdKey := fmt.Sprintf("%s%v", cacheAppUserVolunteerIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, appUserVolunteerIdKey)
	return err
}

func (m *defaultAppUserVolunteerModel) FindOne(ctx context.Context, id int64) (*AppUserVolunteer, error) {
	appUserVolunteerIdKey := fmt.Sprintf("%s%v", cacheAppUserVolunteerIdPrefix, id)
	var resp AppUserVolunteer
	err := m.QueryRowCtx(ctx, &resp, appUserVolunteerIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", appUserVolunteerRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAppUserVolunteerModel) Insert(ctx context.Context, data *AppUserVolunteer) (sql.Result, error) {
	appUserVolunteerIdKey := fmt.Sprintf("%s%v", cacheAppUserVolunteerIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, appUserVolunteerRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.Title, data.Content, data.StartTime, data.EndTime, data.OrderBy, data.DeletedAt)
	}, appUserVolunteerIdKey)
	return ret, err
}

func (m *defaultAppUserVolunteerModel) Update(ctx context.Context, data *AppUserVolunteer) error {
	appUserVolunteerIdKey := fmt.Sprintf("%s%v", cacheAppUserVolunteerIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, appUserVolunteerRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.Title, data.Content, data.StartTime, data.EndTime, data.OrderBy, data.DeletedAt, data.Id)
	}, appUserVolunteerIdKey)
	return err
}

func (m *defaultAppUserVolunteerModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAppUserVolunteerIdPrefix, primary)
}

func (m *defaultAppUserVolunteerModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", appUserVolunteerRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAppUserVolunteerModel) tableName() string {
	return m.table
}
