// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	appUserPurposeCityFieldNames          = builder.RawFieldNames(&AppUserPurposeCity{})
	appUserPurposeCityRows                = strings.Join(appUserPurposeCityFieldNames, ",")
	appUserPurposeCityRowsExpectAutoSet   = strings.Join(stringx.Remove(appUserPurposeCityFieldNames, "`id`", "`update_at`", "`updated_at`", "`update_time`", "`create_at`", "`created_at`", "`create_time`"), ",")
	appUserPurposeCityRowsWithPlaceHolder = strings.Join(stringx.Remove(appUserPurposeCityFieldNames, "`id`", "`update_at`", "`updated_at`", "`update_time`", "`create_at`", "`created_at`", "`create_time`"), "=?,") + "=?"

	cacheAppUserPurposeCityIdPrefix = "cache:appUserPurposeCity:id:"
)

type (
	appUserPurposeCityModel interface {
		Insert(ctx context.Context, data *AppUserPurposeCity) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AppUserPurposeCity, error)
		Update(ctx context.Context, data *AppUserPurposeCity) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAppUserPurposeCityModel struct {
		sqlc.CachedConn
		table string
	}

	AppUserPurposeCity struct {
		Id        int64        `db:"id"`         // 编号
		UserId    int64        `db:"user_id"`    // 用户id
		Name      string       `db:"name"`       // 城市名称
		OrderBy   int64        `db:"order_by"`   // 排序从小到大
		CreateAt  time.Time    `db:"create_at"`  // 创建时间
		UpdateAt  time.Time    `db:"update_at"`  // 更新时间
		DeletedAt sql.NullTime `db:"deleted_at"` // 删除时间
	}
)

func newAppUserPurposeCityModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultAppUserPurposeCityModel {
	return &defaultAppUserPurposeCityModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`app_user_purpose_city`",
	}
}

func (m *defaultAppUserPurposeCityModel) Delete(ctx context.Context, id int64) error {
	appUserPurposeCityIdKey := fmt.Sprintf("%s%v", cacheAppUserPurposeCityIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, appUserPurposeCityIdKey)
	return err
}

func (m *defaultAppUserPurposeCityModel) FindOne(ctx context.Context, id int64) (*AppUserPurposeCity, error) {
	appUserPurposeCityIdKey := fmt.Sprintf("%s%v", cacheAppUserPurposeCityIdPrefix, id)
	var resp AppUserPurposeCity
	err := m.QueryRowCtx(ctx, &resp, appUserPurposeCityIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", appUserPurposeCityRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAppUserPurposeCityModel) Insert(ctx context.Context, data *AppUserPurposeCity) (sql.Result, error) {
	appUserPurposeCityIdKey := fmt.Sprintf("%s%v", cacheAppUserPurposeCityIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, appUserPurposeCityRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.Name, data.OrderBy, data.DeletedAt)
	}, appUserPurposeCityIdKey)
	return ret, err
}

func (m *defaultAppUserPurposeCityModel) Update(ctx context.Context, data *AppUserPurposeCity) error {
	appUserPurposeCityIdKey := fmt.Sprintf("%s%v", cacheAppUserPurposeCityIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, appUserPurposeCityRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.Name, data.OrderBy, data.DeletedAt, data.Id)
	}, appUserPurposeCityIdKey)
	return err
}

func (m *defaultAppUserPurposeCityModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheAppUserPurposeCityIdPrefix, primary)
}

func (m *defaultAppUserPurposeCityModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", appUserPurposeCityRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAppUserPurposeCityModel) tableName() string {
	return m.table
}
