// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	appUserCustomAttributesFieldNames          = builder.RawFieldNames(&AppUserCustomAttributes{})
	appUserCustomAttributesRows                = strings.Join(appUserCustomAttributesFieldNames, ",")
	appUserCustomAttributesRowsExpectAutoSet   = strings.Join(stringx.Remove(appUserCustomAttributesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	appUserCustomAttributesRowsWithPlaceHolder = strings.Join(stringx.Remove(appUserCustomAttributesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAppUserCustomAttributesIdPrefix = "cache:appUserCustomAttributes:id:"
)

type (
	appUserCustomAttributesModel interface {
		Insert(ctx context.Context, data *AppUserCustomAttributes) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AppUserCustomAttributes, error)
		Update(ctx context.Context, data *AppUserCustomAttributes) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAppUserCustomAttributesModel struct {
		sqlc.CachedConn
		table string
	}

	AppUserCustomAttributes struct {
		Id        int64        `db:"id"`         // 编号
		UserId    int64        `db:"user_id"`    // 用户id
		Title     string       `db:"title"`      // 自定义属性标题
		Content   string       `db:"content"`    // 自定义属性内容
		Summary   string       `db:"summary"`    // 自定义属性摘要
		Icon      string       `db:"icon"`       // 自定义属性图标
		StartTime string       `db:"start_time"` // 开始时间
		EndTime   string       `db:"end_time"`   // 结束时间
		OrderBy   int64        `db:"order_by"`   // 排序从小到大
		CreateAt  time.Time    `db:"create_at"`  // 创建时间
		UpdateAt  time.Time    `db:"update_at"`  // 更新时间
		DeletedAt sql.NullTime `db:"deleted_at"` // 删除时间
	}
)

func newAppUserCustomAttributesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAppUserCustomAttributesModel {
	return &defaultAppUserCustomAttributesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`app_user_custom_attributes`",
	}
}

func (m *defaultAppUserCustomAttributesModel) Delete(ctx context.Context, id int64) error {
	appUserCustomAttributesIdKey := fmt.Sprintf("%s%v", cacheAppUserCustomAttributesIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, appUserCustomAttributesIdKey)
	return err
}

func (m *defaultAppUserCustomAttributesModel) FindOne(ctx context.Context, id int64) (*AppUserCustomAttributes, error) {
	appUserCustomAttributesIdKey := fmt.Sprintf("%s%v", cacheAppUserCustomAttributesIdPrefix, id)
	var resp AppUserCustomAttributes
	err := m.QueryRowCtx(ctx, &resp, appUserCustomAttributesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", appUserCustomAttributesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAppUserCustomAttributesModel) Insert(ctx context.Context, data *AppUserCustomAttributes) (sql.Result, error) {
	appUserCustomAttributesIdKey := fmt.Sprintf("%s%v", cacheAppUserCustomAttributesIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, appUserCustomAttributesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.Title, data.Content, data.Summary, data.Icon, data.StartTime, data.EndTime, data.OrderBy, data.DeletedAt)
	}, appUserCustomAttributesIdKey)
	return ret, err
}

func (m *defaultAppUserCustomAttributesModel) Update(ctx context.Context, data *AppUserCustomAttributes) error {
	appUserCustomAttributesIdKey := fmt.Sprintf("%s%v", cacheAppUserCustomAttributesIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, appUserCustomAttributesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.Title, data.Content, data.Summary, data.Icon, data.StartTime, data.EndTime, data.OrderBy, data.DeletedAt, data.Id)
	}, appUserCustomAttributesIdKey)
	return err
}

func (m *defaultAppUserCustomAttributesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAppUserCustomAttributesIdPrefix, primary)
}

func (m *defaultAppUserCustomAttributesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", appUserCustomAttributesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAppUserCustomAttributesModel) tableName() string {
	return m.table
}
